server:
  port: 9111
spring:
  boot:
    admin:
      ui:
        title: JeecgCloud监控中心
      client:
        instance:
          metadata:
            tags:
              environment: local
  security:
    user:
      name: "nacos"
      password: "Wgy23822672@wu"
  application:
    name: jeecg-monitor
  cloud:
    nacos:
      discovery:
        server-addr: @config.server-addr@
        group: @config.group@
        namespace: @config.namespace@
        username: @config.username@
        password: @config.password@
# 服务端点检查
management:
  trace:
    http:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
